In [1]:
import torch
print("CUDA AVAILABLE", torch.cuda.is_available())

CUDA AVAILABLE True


In [2]:
if torch.cuda.is_available():
    print("gpu device name: ", torch.cuda.get_device_name(0))
    print("number of gpu: ", torch.cuda.device_count())
else:
    print("no cuda is detected")

gpu device name:  NVIDIA GeForce RTX 4060 Laptop GPU
number of gpu:  1


In [3]:
import os
import pandas as pd

# Correct path based on your current directory
data_dir = "E:/SurfacePredictor/data"

# List all CSV files in the data directory
csv_files = [f for f in os.listdir(data_dir) if f.endswith('.csv')]

# Loop through each file and display the first 10 rows
for file in csv_files:
    file_path = os.path.join(data_dir, file)
    try:
        df = pd.read_csv(file_path)
        print(f"\n📂 File: {file} — First 10 rows:")
        print(df.head(10))
        input("🔘 Press Enter to continue...")
    except Exception as e:
        print(f"❌ Error reading {file}: {e}")



📂 File: ACRYLIC_1.csv — First 10 rows:
   Time  Resistance
0     1     7254.73
1     2     7893.90
2     3     8091.35
3     4     8130.83
4     5     7933.59
5     6     7961.72
6     7     8358.54
7     8     8730.94
8     9     8557.11
9    10    10247.37


🔘 Press Enter to continue... 



📂 File: BUBBLEWRAP BACK_1.csv — First 10 rows:
   Time  Resistance
0     1     6847.83
1     2     6686.18
2     3     6549.35
3     4     7614.00
4     5     9372.12
5     6     9121.49
6     7    10036.41
7     8     8791.25
8     9     8560.50
9    10     8874.89


🔘 Press Enter to continue... 



📂 File: BUBBLEWRAP FRONT_1.csv — First 10 rows:
   Time  Resistance  Unnamed: 2  Unnamed: 3  Unnamed: 4 Unnamed: 5
0     1     7055.57         NaN         NaN         NaN        NaN
1     2     6979.49         NaN         NaN         NaN        NaN
2     3     7127.05         NaN         NaN         NaN        NaN
3     4     7423.59         NaN         NaN         NaN        NaN
4     5     7858.91         NaN         NaN         NaN        NaN
5     6     9245.95         NaN         NaN         NaN        NaN
6     7     9482.47         NaN         NaN         NaN        NaN
7     8     9367.53         NaN         NaN         NaN          ?
8     9     8369.98         NaN         NaN         NaN        NaN
9    10     9483.76         NaN         NaN         NaN        NaN


🔘 Press Enter to continue... 



📂 File: CARDBOARD_1.csv — First 10 rows:
    1   5271.06  Unnamed: 2  Unnamed: 3 Unnamed: 4
0   2   5346.55         NaN         NaN        NaN
1   3   5501.80         NaN         NaN        NaN
2   4   5531.54         NaN         NaN        NaN
3   5   5545.04         NaN         NaN        NaN
4   6   6592.86         NaN         NaN        NaN
5   7   7895.55         NaN         NaN        NaN
6   8   8019.89         NaN         NaN          ?
7   9   9077.12         NaN         NaN        NaN
8  10   8045.05         NaN         NaN        NaN
9  11  11497.94         NaN         NaN        NaN


🔘 Press Enter to continue... 



📂 File: GLASS_1.csv — First 10 rows:
   Time  Resistance
0     1     7208.84
1     2     7259.89
2     3    11563.53
3     4    13599.23
4     5    13553.84
5     6    14325.82
6     7    15641.78
7     8    11884.10
8     9    17777.72
9    10    15003.44


🔘 Press Enter to continue... 



📂 File: GLOVE_1.csv — First 10 rows:
   Time  Resistance  Unnamed: 2  Unnamed: 3 Unnamed: 4
0     1     7782.02         NaN         NaN        NaN
1     2     7628.49         NaN         NaN        NaN
2     3     7524.28         NaN         NaN        NaN
3     4     7183.81         NaN         NaN        NaN
4     5     7720.31         NaN         NaN        NaN
5     6     9138.75         NaN         NaN        NaN
6     7     8881.72         NaN         NaN        NaN
7     8     9897.66         NaN         NaN          ?
8     9     8701.35         NaN         NaN        NaN
9    10    14879.96         NaN         NaN        NaN


🔘 Press Enter to continue... 



📂 File: MARBLE_1.csv — First 10 rows:
   Time  Resistance
0     1     6820.29
1     2     5895.30
2     3     5896.01
3     4     8067.55
4     5   209707.92
5     6    13854.78
6     7     4522.74
7     8     3087.20
8     9    14389.56
9    10     4609.92


🔘 Press Enter to continue... 



📂 File: METAL_1.csv — First 10 rows:
   Time  Resistance
0     1     4967.72
1     2     4964.07
2     3     4917.59
3     4     4881.40
4     5     4909.83
5     6     5283.04
6     7     6088.49
7     8     5869.14
8     9     6261.73
9    10     7327.21


🔘 Press Enter to continue... 



📂 File: PAPER_1.csv — First 10 rows:
   Time  Resistance
0     1     8824.68
1     2    13266.33
2     3    16550.91
3     4    16923.30
4     5    20989.39
5     6    17369.66
6     7     7754.21
7     8    10820.73
8     9    13169.10
9    10    18509.35


🔘 Press Enter to continue... 



📂 File: SMOOTH WOODEN_1.csv — First 10 rows:
   Time  Resistance
0     1     6293.07
1     2     6246.57
2     3     6338.27
3     4     6673.42
4     5     6489.70
5     6     9311.93
6     7     8121.70
7     8    18523.31
8     9    14516.83
9    10     6838.91


🔘 Press Enter to continue... 


In [4]:
import os
import pandas as pd
import numpy as np

# ✅ Update to your actual project path
folder_path = "E:/SurfacePredictor/data"
csv_files = [f for f in os.listdir(folder_path) if f.endswith('.csv')]

cleaned_dfs = []

for file in csv_files:
    try:
        file_path = os.path.join(folder_path, file)
        df = pd.read_csv(file_path)

        # Replace '?' with NaN and drop all-NaN columns
        df.replace("?", np.nan, inplace=True)
        df.dropna(axis=1, how='all', inplace=True)

        # Drop unnamed columns
        df = df.loc[:, ~df.columns.str.contains("^Unnamed", na=False)]

        # Keep only numeric columns
        df = df.select_dtypes(include=[np.number])

        # Add default Time column if only 1 column exists
        if df.shape[1] == 1:
            df.insert(0, "Time", range(1, len(df)+1))

        # Standardize column names
        df.columns = ['Time', 'Resistance'] + list(df.columns[2:])

        # Label each row with surface type extracted from filename
        surface_label = file.replace(".csv", "").split("_")[0].upper()
        df["Surface"] = surface_label

        # Add cleaned dataframe to list
        cleaned_dfs.append(df)

    except Exception as e:
        print(f"❌ Error in {file}: {e}")

# ✅ Combine all cleaned CSVs into one
if cleaned_dfs:
    combined_df = pd.concat(cleaned_dfs, ignore_index=True)
    combined_df.to_csv(os.path.join(folder_path, "Cleaned_Surface_Data.csv"), index=False)
    print("✅ Cleaning completed! File saved as 'Cleaned_Surface_Data.csv'")
    print(combined_df.head())

else:
    print("❌ No valid CSVs were processed.")


✅ Cleaning completed! File saved as 'Cleaned_Surface_Data.csv'
   Time  Resistance  Surface
0     1     7254.73  ACRYLIC
1     2     7893.90  ACRYLIC
2     3     8091.35  ACRYLIC
3     4     8130.83  ACRYLIC
4     5     7933.59  ACRYLIC


C:\Users\Nikhil S\AppData\Local\Temp\ipykernel_24764\4049073602.py:17: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.replace("?", np.nan, inplace=True)
C:\Users\Nikhil S\AppData\Local\Temp\ipykernel_24764\4049073602.py:17: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.replace("?", np.nan, inplace=True)
C:\Users\Nikhil S\AppData\Local\Temp\ipykernel_24764\4049073602.py:17: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result

In [7]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report , confusion_matrix

In [8]:
df = pd.read_csv("E:/SurfacePredictor/data/Cleaned_Surface_Data.csv")

# Prepare features and labels
X = df[['Resistance']]        # Using Resistance as the only feature
y = df['Surface']             # Surface labels as targets

# Encode categorical surface labels into numbers
le = LabelEncoder()
y_encoded = le.fit_transform(y)

# Split into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y_encoded, test_size=0.2, random_state=42)

# Train a Random Forest Classifier
clf = RandomForestClassifier(n_estimators=100, random_state=42)
clf.fit(X_train, y_train)

# Predict and evaluate
y_pred = clf.predict(X_test)

# Show evaluation metrics
print("📊 Classification Report:")
print(classification_report(y_test, y_pred, target_names=le.classes_))

print("📉 Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

📊 Classification Report:
                  precision    recall  f1-score   support

         ACRYLIC       0.12      0.10      0.11        30
 BUBBLEWRAP BACK       0.23      0.23      0.23        53
BUBBLEWRAP FRONT       0.16      0.11      0.13        38
       CARDBOARD       0.31      0.32      0.32        37
           GLASS       0.12      0.16      0.14        25
           GLOVE       0.18      0.13      0.15        30
          MARBLE       0.58      0.67      0.62        39
           METAL       0.26      0.25      0.25        32
           PAPER       0.29      0.44      0.35        16
   SMOOTH WOODEN       0.22      0.24      0.23        38

        accuracy                           0.26       338
       macro avg       0.25      0.26      0.25       338
    weighted avg       0.25      0.26      0.26       338

📉 Confusion Matrix:
[[ 3  5  1  2  4  5  1  3  1  5]
 [ 5 12  6  5  4  4  3  5  1  8]
 [ 0 11  4  4  0  1 11  3  0  4]
 [ 5  5  2 12  3  1  2  5  1  1]
 [ 2  2 

In [9]:
!pip install xgboost

   ---------------------------------------- 0.0/150.0 MB ? eta -:--:--
   - -------------------------------------- 4.2/150.0 MB 22.9 MB/s eta 0:00:07
   -- ------------------------------------- 9.2/150.0 MB 24.8 MB/s eta 0:00:06
   --- ------------------------------------ 14.2/150.0 MB 24.0 MB/s eta 0:00:06
   ---- ----------------------------------- 18.6/150.0 MB 23.5 MB/s eta 0:00:06
   ------ --------------------------------- 23.6/150.0 MB 23.7 MB/s eta 0:00:06
   ------- -------------------------------- 29.1/150.0 MB 24.3 MB/s eta 0:00:05
   --------- ------------------------------ 34.3/150.0 MB 24.2 MB/s eta 0:00:05
   ---------- ----------------------------- 39.6/150.0 MB 24.4 MB/s eta 0:00:05
   ----------- ---------------------------- 44.3/150.0 MB 24.3 MB/s eta 0:00:05
   ------------- -------------------------- 48.8/150.0 MB 24.1 MB/s eta 0:00:05
   -------------- ------------------------- 54.0/150.0 MB 24.2 MB/s eta 0:00:04
   --------------- ------------------------ 59.2/15

In [10]:
!pip install imbalanced-learn


   ---------------------------------------- 0/2 [sklearn-compat]
   -------------------- ------------------- 1/2 [imbalanced-learn]
   -------------------- ------------------- 1/2 [imbalanced-learn]
   -------------------- ------------------- 1/2 [imbalanced-learn]
   -------------------- ------------------- 1/2 [imbalanced-learn]
   -------------------- ------------------- 1/2 [imbalanced-learn]
   -------------------- ------------------- 1/2 [imbalanced-learn]
   -------------------- ------------------- 1/2 [imbalanced-learn]
   -------------------- ------------------- 1/2 [imbalanced-learn]
   ---------------------------------------- 2/2 [imbalanced-learn]



In [12]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from xgboost import XGBClassifier
from sklearn.metrics import classification_report, confusion_matrix
from imblearn.over_sampling import SMOTE

# 1️⃣ Load Cleaned Data
df = pd.read_csv("E:/SurfacePredictor/data/Cleaned_Surface_Data.csv")

# 2️⃣ Remove outliers (very high resistance)
df = df[df['Resistance'] < 50000]

# 3️⃣ Feature Engineering
df['Resistance_diff'] = df['Resistance'].diff().fillna(0)
df['Rolling_mean_5'] = df['Resistance'].rolling(5).mean().fillna(method='bfill')
df['Rolling_std_5'] = df['Resistance'].rolling(5).std().fillna(method='bfill')

# 4️⃣ Prepare Features & Labels
X = df[['Resistance', 'Resistance_diff', 'Rolling_mean_5', 'Rolling_std_5']]
y = df['Surface']
le = LabelEncoder()
y_encoded = le.fit_transform(y)

# 5️⃣ Balance Dataset with SMOTE
X_resampled, y_resampled = SMOTE(random_state=42).fit_resample(X, y_encoded)

# 6️⃣ Train-Test Split
X_train, X_test, y_train, y_test = train_test_split(X_resampled, y_resampled, test_size=0.2, random_state=42)

# 7️⃣ Train XGBoost Classifier
model = XGBClassifier(use_label_encoder=False, eval_metric='mlogloss', random_state=42)
model.fit(X_train, y_train)

# 8️⃣ Evaluate
y_pred = model.predict(X_test)

print("✅ Classification Report:")
print(classification_report(y_test, y_pred, target_names=le.classes_))
print("📉 Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

C:\Users\Nikhil S\AppData\Local\Temp\ipykernel_24764\3333709113.py:17: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['Rolling_mean_5'] = df['Resistance'].rolling(5).mean().fillna(method='bfill')
C:\Users\Nikhil S\AppData\Local\Temp\ipykernel_24764\3333709113.py:18: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['Rolling_std_5'] = df['Resistance'].rolling(5).std().fillna(method='bfill')
E:\SurfacePredictor\surface\lib\site-packages\xgboost\training.py:183: UserWarning: [01:13:14] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:738: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)


✅ Classification Report:
                  precision    recall  f1-score   support

         ACRYLIC       0.53      0.65      0.59        37
 BUBBLEWRAP BACK       0.51      0.40      0.45        52
BUBBLEWRAP FRONT       0.82      0.80      0.81        69
       CARDBOARD       0.65      0.69      0.67        45
           GLASS       0.68      0.75      0.71        48
           GLOVE       0.60      0.66      0.62        38
          MARBLE       0.84      0.85      0.85        48
           METAL       0.64      0.67      0.65        52
           PAPER       0.75      0.80      0.77        54
   SMOOTH WOODEN       0.77      0.57      0.65        53

        accuracy                           0.69       496
       macro avg       0.68      0.68      0.68       496
    weighted avg       0.69      0.69      0.69       496

📉 Confusion Matrix:
[[24  4  0  2  0  3  0  0  0  4]
 [ 5 21  3  8  3  5  0  4  3  0]
 [ 0  1 55  1  0  2  5  5  0  0]
 [ 2  4  2 31  0  0  0  5  0  1]
 [ 1  1 

In [13]:
!pip install optuna

   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------------------------------------- 2.1/2.1 MB 29.8 MB/s eta 0:00:00

   ---------------------------------------- 0/6 [Mako]
   ---------------------------------------- 0/6 [Mako]
   ---------------------------------------- 0/6 [Mako]
   ------ --------------------------------- 1/6 [greenlet]
   ------ --------------------------------- 1/6 [greenlet]
   -------------------- ------------------- 3/6 [sqlalchemy]
   -------------------- ------------------- 3/6 [sqlalchemy]
   -------------------- ------------------- 3/6 [sqlalchemy]
   -------------------- ------------------- 3/6 [sqlalchemy]
   -------------------- ------------------- 3/6 [sqlalchemy]
   -------------------- ------------------- 3/6 [sqlalchemy]
   -------------------- ------------------- 3/6 [sqlalchemy]
   -------------------- ------------------- 3/6 [sqlalchemy]
   -------------------- ------------------- 3/6 [sqlalchemy]
   ------------------

In [14]:
df['Slope'] = df['Resistance'].diff().fillna(0)  # Rate of change
df['EMA'] = df['Resistance'].ewm(span=5).mean()  # Exponential Moving Average
df['Max_Min'] = df['Resistance'].rolling(5).max() - df['Resistance'].rolling(5).min()

In [15]:
import optuna
from xgboost import XGBClassifier

def objective(trial):
    params = {
        'max_depth': trial.suggest_int('max_depth', 3, 10),
        'learning_rate': trial.suggest_float('learning_rate', 0.01, 0.3),
        'n_estimators': trial.suggest_int('n_estimators', 50, 300),
        'subsample': trial.suggest_float('subsample', 0.6, 1.0),
        'colsample_bytree': trial.suggest_float('colsample_bytree', 0.6, 1.0)
    }
    model = XGBClassifier(**params, use_label_encoder=False, eval_metric='mlogloss')
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

study = optuna.create_study(direction='maximize')
study.optimize(objective, n_trials=30)

E:\SurfacePredictor\surface\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
[I 2025-05-29 01:14:43,438] A new study created in memory with name: no-name-813eb479-45ba-4b41-b228-4956b7596b59
E:\SurfacePredictor\surface\lib\site-packages\xgboost\training.py:183: UserWarning: [01:14:43] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:738: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2025-05-29 01:14:44,045] Trial 0 finished with value: 0.6774193548387096 and parameters: {'max_depth': 5, 'learning_rate': 0.21035469481847055, 'n_estimators': 185, 'subsample': 0.6752528924355395, 'colsample_bytree': 0.8068453721083737}. Best is trial 0 with value: 0.6774193548387096.
E:\SurfacePredictor\surface\lib\site-packages\xgboost\training.py:183: UserWarning: [

In [19]:
best_model = XGBClassifier(
    max_depth=14,
    learning_rate=0.15,
    n_estimators=150,
    subsample=0.9,
    colsample_bytree=0.8,
    gamma=0.1,
    reg_alpha=0.2,
    reg_lambda=1.0,
    tree_method='gpu_hist',
    predictor='gpu_predictor',
    eval_metric='mlogloss',
    random_state=42
)


In [20]:
from sklearn.metrics import classification_report, confusion_matrix

print("✅ Classification Report:")
print(classification_report(y_test, y_pred, target_names=le.classes_))
print("📉 Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

✅ Classification Report:
                  precision    recall  f1-score   support

         ACRYLIC       0.53      0.65      0.59        37
 BUBBLEWRAP BACK       0.51      0.40      0.45        52
BUBBLEWRAP FRONT       0.82      0.80      0.81        69
       CARDBOARD       0.65      0.69      0.67        45
           GLASS       0.68      0.75      0.71        48
           GLOVE       0.60      0.66      0.62        38
          MARBLE       0.84      0.85      0.85        48
           METAL       0.64      0.67      0.65        52
           PAPER       0.75      0.80      0.77        54
   SMOOTH WOODEN       0.77      0.57      0.65        53

        accuracy                           0.69       496
       macro avg       0.68      0.68      0.68       496
    weighted avg       0.69      0.69      0.69       496

📉 Confusion Matrix:
[[24  4  0  2  0  3  0  0  0  4]
 [ 5 21  3  8  3  5  0  4  3  0]
 [ 0  1 55  1  0  2  5  5  0  0]
 [ 2  4  2 31  0  0  0  5  0  1]
 [ 1  1 

In [23]:
from xgboost import XGBClassifier

best_model = XGBClassifier(
    max_depth=14,
    learning_rate=0.15,
    n_estimators=150,
    subsample=0.9,
    colsample_bytree=0.8,
    gamma=0.1,
    reg_alpha=0.2,
    reg_lambda=1.0,
    tree_method='hist',        # ✅ new way
    device='cuda',             # ✅ enables GPU
    eval_metric='mlogloss',
    random_state=42
)

best_model.fit(X_train, y_train)


XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=0.8, device='cuda', early_stopping_rounds=None,
              enable_categorical=False, eval_metric='mlogloss',
              feature_types=None, feature_weights=None, gamma=0.1,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.15, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=14, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=150, n_jobs=None,
              num_parallel_tree=None, ...)

In [24]:
import pandas as pd
import numpy as np
from collections import Counter

# 1️⃣ Load GLOVE_2.csv from the updated path
glove_test = pd.read_csv("E:/SurfacePredictor/data/GLOVE_2.csv")

# 2️⃣ Clean and preprocess
glove_test = glove_test.replace("?", np.nan).dropna(axis=1, how='all')
glove_test = glove_test.select_dtypes(include=[np.number])

# 3️⃣ Ensure correct column names
glove_test.columns = ['Time', 'Resistance']  # Adjust this if more columns exist

# 4️⃣ Feature generation (same as training pipeline)
glove_test['Resistance_diff'] = glove_test['Resistance'].diff().fillna(0)
glove_test['Rolling_mean_5'] = glove_test['Resistance'].rolling(5).mean().fillna(method='bfill')
glove_test['Rolling_std_5'] = glove_test['Resistance'].rolling(5).std().fillna(method='bfill')

# 5️⃣ Select features
X_glove = glove_test[['Resistance', 'Resistance_diff', 'Rolling_mean_5', 'Rolling_std_5']]

# 6️⃣ Predict using the best trained model
preds = best_model.predict(X_glove)
pred_labels = le.inverse_transform(preds)

# 7️⃣ Summary of predictions
print("🧠 GLOVE_2 Predictions Summary:")
print(Counter(pred_labels))


🧠 GLOVE_2 Predictions Summary:
Counter({'GLOVE': 127, 'ACRYLIC': 4, 'BUBBLEWRAP BACK': 3, 'CARDBOARD': 2, 'SMOOTH WOODEN': 2, 'GLASS': 1})


C:\Users\Nikhil S\AppData\Local\Temp\ipykernel_24764\3236349553.py:9: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  glove_test = glove_test.replace("?", np.nan).dropna(axis=1, how='all')
C:\Users\Nikhil S\AppData\Local\Temp\ipykernel_24764\3236349553.py:17: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  glove_test['Rolling_mean_5'] = glove_test['Resistance'].rolling(5).mean().fillna(method='bfill')
C:\Users\Nikhil S\AppData\Local\Temp\ipykernel_24764\3236349553.py:18: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  glove_test['Rolling_std_5'] = glove_test['Resistance'].rolling(5).std().

In [26]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score


y_true = ['GLOVE'] * len(pred_labels)

y_pred = pred_labels

acc = accuracy_score(y_true, y_pred)
print(f"✅ Accuracy on GLOVE_2: {acc:.4f} ({acc*100:.2f}%)")

✅ Accuracy on GLOVE_2: 0.9137 (91.37%)
